feat: 추천 리스트 조회
prgrms-web-devcourse/Team-6Jeans-Hype-FE pull request #17
Opened 2023-02-22 05:52 UTC by Park-min-hyoung

## 📌 이슈 번호

- close #15

## 👩‍💻 작업 내용

- 리스트 리스트 조회
    - [x]  react-query 통해서 더미 데이터 불러오기
    - [x]  더미데이터를 통해 리스트 render
    - [x]  type 설정
    - [x]  로딩중 표시(나중에 스켈레톤)
    - [x]  특정 글 클릭하면 글 상세페이지로 이동

2023-02-22 05:53 UTC, NamJwong commented on src/components/post/index.tsx
> +          >
key 안 넣어줘서 빌드 터졌네용 !!

2023-02-22 06:49 UTC, ksh-jsx approved these changes

2023-02-22 16:53 UTC, NamJwong requested changes

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/index.tsx
> +        <div>로딩 중 입니다~</div>
p5; 오옹 혹시 로딩 디자인 mvp 단에서 안 나오게 되면 일단 빈 프래그먼트 리턴하게 하면 될 것 같아요~

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/index.tsx
> +  const { data, isLoading } = useQuery<ListInfo[]>(['postfeed'], getPostFeedData);
```suggestion
  const { data: postList, isLoading } = useQuery<ListInfo[]>(['postfeed'], getPostFeedData);
```
p2; 이렇게 data 변수 네이밍 바꿔주면 코드 이해하기 더 좋을 것 같아요!

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/types.ts
> +export interface ListInfo {
p2; 이거 하나의 post 정보 아닌가요? 그러면 Post 라는 이름이 좋을 것 같아요!

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/index.tsx
> +    else router.push('/auth', '/auth');
p4; as 파라미터 꼭 넣어줘야 할까요??

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/index.tsx
> +    else router.push('/auth', '/auth');
p1; 조회는 로그인 없이도 다 가능해서 이 처리 안 해주셔도 돼요~

2023-02-22 16:53 UTC, NamJwong commented on src/components/post/index.tsx
> +    else router.push('/auth', '/auth');
그리고 참고로 제가 인증 관련 구현하면서 접근 권한 관련된 공통 모듈 만들어보려고 해요!

2023-02-22 17:12 UTC, NamJwong commented on src/components/post/index.tsx
> +            key={index}
p3; 지금으로썬 문제 없지만 기능이 확장됨에 따라 문제 될 여지가 있으니 index 말고 id 값을 key로 사용하는 게 어떨까요?

2023-02-23 06:23 UTC, NamJwong approved these changes

2023-02-23 15:41 UTC, ksh-jsx approved these changes

2023-02-24 07:43 UTC, merged