Feature/#8 create featured feed page
prgrms-web-devcourse/Team-6Jeans-Hype-FE pull request #19
Opened 2023-02-22 07:13 UTC by ksh-jsx

## 📌 이슈 번호

- close #8 

## 👩‍💻 작업 내용
- 추천 피드 생성 페이지 만들기
  - 음악 검색 컴포넌트 제작 (musicSearcher)
    - useMusicList hooks 사용
    - input에 검색어 입력 시, tmpKeyword에 value 저장되고 debounce 지정 시간 이후에 Keyword 변경 -> react-query를 통해 keyword 변경 인식되면 api에서 데이터 불러와서 리스트로 렌더링
    - 리스트에서 음악 클릭 시, 해당 정보 렌더링
  - 설명(추천이유), 대결 가능(toggle버튼)도 입력받을 수 있음
    -  common 디렉토리에 toggle 컴포넌트 생성
 - 로딩 처리용 스켈레톤 컴포넌트 생성

2023-02-22 17:38 UTC, NamJwong requested changes
고생하셨습니다! 이렇게 빠른 시간 내에 뚝딱뚝딱 완성하시다니 진짜 대단합니당👍

그런데 성현님 PR 단위를 다음에는 훨씬 작게 작게 .. 올려주시면 리뷰하기 수월할 것 같습니다 🥺

PR 단위가 작아야 하는 이유 참고
- https://soojin.ro/review/small-cls
- https://engineering.linecorp.com/ko/blog/effective-codereview/#keep-changes-small
- https://blog.banksalad.com/tech/banksalad-code-review-culture/#%EC%9E%91%EC%9D%80-pr-%EA%B7%9C%EC%B9%99

\+ 다 지금 당장 크리티컬한 문제는 아니어서 어프룹 할려고 했는데 실수로 request changes로 달았어용^^..

2023-02-22 17:38 UTC, NamJwong commented on src/components/common/Toggle.tsx
> +export default memo(Toggle, (prev, next) => prev.on === next.on);
p3; useToggle.ts에 리뷰 달았던 useCallback 이슈와 비슷하게 이또한 React.memo가 불필요해보여요
컴포넌트가 무겁지도 않고 어차피 on이라는 prop으로 자주 렌더링 될 컴포넌트여서요

아래 글 참고해주세요!
https://yohanpro.com/posts/react/react-memo

2023-02-22 17:38 UTC, NamJwong commented on src/components/common/skeleton/Base.tsx
> +const Base = styled.div`
p4; 쓰는 입장에선 이름 확실한 게 좋아서 `SkeletonBase`가 어떨지 제안해봅니다~

2023-02-22 17:38 UTC, NamJwong commented on src/components/common/skeleton/Box.tsx
> +const Box = styled(Base)`
p4; 여기도 `SkeletonBox` 면 더 좋을 것 같아요

2023-02-22 17:38 UTC, NamJwong commented on src/components/common/skeleton/MusicList.tsx
> +const MusicList = ({ line = 3, ...props }) => {
p4; MusicListSkeleton 이면 더 좋을 것 같습니다

2023-02-22 17:38 UTC, NamJwong commented on src/components/common/skeleton/index.tsx
> +};
이건 어디에서 사용되는 거예요??

2023-02-22 17:38 UTC, NamJwong commented on src/components/post/create/musicSearcher/RenderMusicList.tsx
> +function RenderMusicList({ onClickInMusicList, onChangeMusicInfo, keywords }: Props) {
p3; render하는 건 컴포넌트의 기본 동작인데 그냥 MusicList라고 하면 되지 않을까요?

2023-02-22 17:38 UTC, NamJwong commented on src/hooks/useCreatePost.ts
> +    console.log(postInfo);
p1; 꼭 필요하지 않은 console.log는 빼고 올려주세요!

2023-02-22 17:38 UTC, NamJwong approved these changes

2023-02-22 17:44 UTC, NamJwong requested changes
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73823388/220711595-b4c00b6a-f336-4e2c-a770-c38aa8cfc4b8.png">


앗 실행해보니 아이유 좋은날 로 검색하면 이 오류로 터지는데 확인해봐야 할 것 같아요!

2023-02-23 05:32 UTC, NamJwong approved these changes

2023-02-23 05:33 UTC, Park-min-hyoung approved these changes

2023-02-23 06:39 UTC, merged