fix: 글로벌 배경 색상 변경
prgrms-web-devcourse/Team-6Jeans-Hype-FE pull request #38
Opened 2023-02-24 09:37 UTC by NamJwong

## 📌 이슈 번호

- close #37 

## 👩‍💻 작업 내용

- 잘못 설정했던 색상값 바꾸기
- 배경 색이 다른 페이지가 있을 경우 어색하지 않도록, max-width 내에서만 배경 색상 적용되도록 수정

2023-02-24 11:50 UTC, Park-min-hyoung approved these changes

2023-02-25 08:42 UTC, ksh-jsx approved these changes

2023-02-26 15:44 UTC, dazzel3 requested changes
확인 부탁해용ㅎㅎ

2023-02-26 15:44 UTC, dazzel3 commented on src/styles/global.ts
> +    background-color: #fbfbff;
```suggestion
    background-color: ${COLOR.background};
```
색상은 color.ts에 선언한 것을 사용해서 이렇게 작성하는 것이 좋을 것 같아용!

2023-02-27 00:18 UTC, dazzel3 approved these changes
확인했습니다!

2023-02-27 05:34 UTC, merged